### ISSUE TITLE
Expose NetcodeSocket

### ISSUE THREAD

**Issue by benjamin-kirkbride** [benny-n/netcode#10]
Similar to #7

I am working on Python bindings for this library, but typing a `Client` requires access to `NetcodeSocket`.

![image](https://github.com/user-attachments/assets/23570ef2-12d7-4610-95b3-f81a0fedee03)

**Comment by benny-n** [comment]
Hi @benjamin-kirkbride ,

I am trying to understand your use-case, are you trying to return a `Client` with a custom transceiver? That can be done with `Client::with_config_and_transceiver()` which was merged in #8

**Comment by benjamin-kirkbride** [comment]
Not exactly. I'm trying to create as close as possible to a 1:1 mapping of
the Rust API to Python bindings.

To do this, I (believe) must create a wrapper, PyClass (
https://pyo3.rs/main/class) which internally contains the rust class. The
rust class must be annotated/typed/generic-ed with the same thing that
::new will.

I don't really know Rust, I wrote my very first line of rust yesterday, so
I apologize if any of this is really dumb.

**Comment by benjamin-kirkbride** [comment]
Basically if I write:
```rust
    #[pyclass]
    struct PyClient {
        inner: Client,
    }
```

I get the following error:
> missing generics for struct `netcode::Client`

It seems like I need to instead write:
```rust
    #[pyclass]
    struct PyClient {
        inner: Client<NetcodeSocket>,
    }
```

But `NetcodeSocket` is not public.

Please let me know if this doesn't make sense. I believe the high level question here, independent of my efforts to make Python bindings, is "How would one define a struct that contains a field with `Client`, as returned by `Client::new`?

**Comment by benjamin-kirkbride** [comment]
Basically, because `Client::new` returns `Client<NetcodeSocket>`, I need to be able to access `NetcodeSocket` to crease a struct field that can contain the result of `Client::new`... I think?

**Comment by benjamin-kirkbride** [comment]
Okay, I figured out how to do it with a "normal" struct:
```rust
    struct MyClient<T: Transceiver> {
        inner: Client<T>,
    }
```

Issue is, PyO3 does not support wrapping generic structs: https://pyo3.rs/v0.22.2/class.html#no-generic-parameters

So I'm back to needing `NetcodeSocket` :sweat:
