### ISSUE TITLE
Trait Transceiver is not public

### ISSUE THREAD

**Issue by cBournhonesque** [benny-n/netcode#7]
Hi,

I'd like to use your netcode implementation with a custom transport layer, but the transceiver module doesn't seem to be public. 
Are there any plans to make it public?

**Comment by benny-n** [comment]
Hi @cBournhonesque 

This trait's main purpose was to allow easy and modular testing and I didn't think it would be of any use as public, that's why it was made private.

Having said that I see no problem at all in making it public :)

Out of curiosity, could you elaborate about your specific use-case?

**Comment by cBournhonesque** [comment]
I wanted (just to learn rust + networking) to create a networking library where I would work on passing messages reliably + fragmentation (equivalent of reliable.io if I understand correctly), but use your library for all the logic of establishing a secure connection (equivalent of netcode.io).

I'd like my library to be transport-agnostic so that I could potentially use transports that are compatible with browsers via wasm (webtransport or webrtc, potentially?)

Here's an inspiration which is transport-agnostic! https://github.com/naia-lib/naia/tree/main

**Comment by cBournhonesque** [comment]
Awesome; is there a way I could chat with you? Maybe on discord?

**Comment by benny-n** [comment]
Sure :)
My discord is **wicked_lama**

**Comment by benny-n** [comment]
@cBournhonesque  I opened #8 to address this issue.
It would be great if you could try it out and see if it suits your use case!
